name: Go CLI Release

on:
  workflow_call:
    inputs:
      go_version:
        description: 'Go version to use'
        type: string
        default: '1.26.x'
    secrets:
      PLATFORM_ASSISTANT_GH_APP_ID:
        required: true
      PLATFORM_ASSISTANT_GH_APP_PRIVATE_KEY:
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: kubeadapt/public-actions/.github/actions/golang-cli-release@main
        with:
          go_version: ${{ inputs.go_version }}
          PLATFORM_ASSISTANT_GH_APP_ID: ${{ secrets.PLATFORM_ASSISTANT_GH_APP_ID }}
          PLATFORM_ASSISTANT_GH_APP_PRIVATE_KEY: ${{ secrets.PLATFORM_ASSISTANT_GH_APP_PRIVATE_KEY }}
